spring.application.name=sistema-agendamento-api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/scheduling}
spring.datasource.username=${DB_USER:scheduling}
spring.datasource.password=${DB_PASSWORD:scheduling}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.port=8080
